language: php
php:
 - 7.0
 - 7.1
 - 7.2
before_script:
 - composer install --dev
 - if [ $(phpenv version-name) = "7.0" ]; wget https://github.com/infection/infection/releases/download/0.9.0/infection.phar; fi
 - if [ $(phpenv version-name) = "7.0" ]; wget https://github.com/infection/infection/releases/download/0.9.0/infection.phar.pubkey; fi
 - if [ $(phpenv version-name) = "7.0" ]; chmod +x infection.phar; fi
script:
 - phpunit --configuration phpunit.xml
 - if [ $(phpenv version-name) = "7.0" ]; ./infection.phar --min-msi=48 --threads=4; fi
after_script:
 - if [ $(phpenv version-name) = "7.0" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then CODECLIMATE_REPO_TOKEN="15813799526ee16462ebffc4f7f45d8692e07e002287190bc414dd1ba548dc41" vendor/bin/test-reporter; fi

