language: php
php:
- 7.1
- 7.2
before_script: composer install --dev
script: phpunit --configuration phpunit.xml
after_script:
  - if [ $(phpenv version-name) = "7.1" ]; then CODECLIMATE_REPO_TOKEN="15813799526ee16462ebffc4f7f45d8692e07e002287190bc414dd1ba548dc41" vendor/bin/test-reporter; fi


