language: php
php:
 - 7.0
 - 7.1
 - 7.2
before_script:
 - composer install --dev
 - if [ $(phpenv version-name) = "7.0" ]; then wget https://github.com/infection/infection/releases/download/0.9.0/infection.phar; fi
 - if [ $(phpenv version-name) = "7.0" ]; then wget https://github.com/infection/infection/releases/download/0.9.0/infection.phar.pubkey; fi
 - if [ $(phpenv version-name) = "7.0" ]; then chmod +x infection.phar; fi
script:
 - phpunit --configuration phpunit.xml
 - if [ $(phpenv version-name) = "7.0" ]; then ./infection.phar --min-msi=75 --min-covered-msi=75 --threads=4; fi
after_script:
 - if [ $(phpenv version-name) = "7.0" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then vendor/bin/test-reporter -v; fi

