language: php
php:
- 5.5
- 5.4
before_script: composer install --dev
script: phpunit --configuration phpunit.xml
after_script:
- ./codeclimate.sh

addons:
  code_climate:
    repo_token:
      secure: RMJTao9mbMTI5MvdLVJ20qAFk9jrOQpOnYHGBckwBA3bPCbyGh5zo1wU5jHsfVRyS7h7wvrlUuE8FynQL3P7wDwgFPIMrvOTLbpac5IBhz1AjEDCumcxdvsPgBrw7hbmJpyEQbLd6Fga0emBgVbJ3XVuUvVSc1EAOubZzQsQRSdfU0YVo9MIUTp5dGZSlxh+bQznpquJkNf+VhBju1O37NNNKPomiUYZHqWoBlso2V1jhT19kY6Izl+SWvTPyvVlKIamFloKNZIR+fv20wZ0Khkje4IhNWsaHW9CcxZhxl5NLcnsVrsrvExkfkDl/QjLa8tn71mWMc+q3NUX04Xm+ut+BLCigHKm8+J9Ofh6/55y7Kryki/OXoT3DisBQwKSdAjD7bHbd5SJHP17pbegbL32E72QTpE8wsPnVKqSZC8rusZHP2Ic2trOZxNksO2OOKUGwsspbYI0A1lDz1BsRz4Q75LN1UHUQk48TCn0G1+/wsdthpVVKTytOhtKdCQ4qmkdqMwQV60J+NVzIze0c+UJBuQsKFdSIYnXyUCpD99Oz4cJnUu6FsrenwTLTRsPXClpyeLXd5aw/LxzVHjlZTwlCO9agbdK6jr5cM9Xr/L6a2kq2VLFPQDMuiXeiJ2PQMMLQSGREp6Z60Sg2UgcJ4TkGg+P+rfPHffE7EIfM0s=
